packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/node": ^22.13.14
  "@cloudflare/workers-types": ^4.20251213.0
  "@orpc/server": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/zod": ^1.12.2
  better-auth: ^1.4.9
  alchemy: ^0.82.1
  wrangler: ^4.54.0
  "@orpc/client": ^1.12.2
